In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good Developer',
      'understand the meaning of words',
      'your videos are good',]

In [3]:
voc_size=10000

In [4]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [5]:
one_hot_repr

[[3639, 6726, 8371, 7021],
 [3639, 6726, 8371, 6823],
 [3639, 1852, 8371, 800],
 [6061, 5276, 9673, 4842, 6764],
 [6061, 5276, 9673, 4842, 8813],
 [3773, 3639, 8845, 8371, 1664],
 [3342, 3237, 1696, 4842]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)  

[[   0    0    0    0 3639 6726 8371 7021]
 [   0    0    0    0 3639 6726 8371 6823]
 [   0    0    0    0 3639 1852 8371  800]
 [   0    0    0 6061 5276 9673 4842 6764]
 [   0    0    0 6061 5276 9673 4842 8813]
 [   0    0    0 3773 3639 8845 8371 1664]
 [   0    0    0    0 3342 3237 1696 4842]]


In [10]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Development\Project4\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step


array([[[ 0.00811927,  0.02765963,  0.02551276,  0.03798034,
          0.0402488 , -0.03271046,  0.01612078,  0.04814399,
          0.02890563, -0.03047484],
        [ 0.00811927,  0.02765963,  0.02551276,  0.03798034,
          0.0402488 , -0.03271046,  0.01612078,  0.04814399,
          0.02890563, -0.03047484],
        [ 0.00811927,  0.02765963,  0.02551276,  0.03798034,
          0.0402488 , -0.03271046,  0.01612078,  0.04814399,
          0.02890563, -0.03047484],
        [ 0.00811927,  0.02765963,  0.02551276,  0.03798034,
          0.0402488 , -0.03271046,  0.01612078,  0.04814399,
          0.02890563, -0.03047484],
        [-0.02324467,  0.01196536, -0.02081801,  0.00709129,
         -0.01924383, -0.00396235,  0.03037271, -0.01650316,
          0.00073307, -0.02811946],
        [ 0.04392843,  0.04726661, -0.01807226,  0.03029242,
          0.00656004,  0.01985124, -0.01460569, -0.00382786,
         -0.00917829,  0.04740368],
        [ 0.03525129, -0.00229716, -0.01486355, -0.0